#!/bin/bash
#
echo "Sisesta kasutajanimi"
read kasutaja
andmebaas=$kasutaja'_andmebaas'
date=$(date +%y-%m-%d.%H-%M.$andmebaas.backup.sql)
mysqldump  --user=root --password=qwerty $andmebaas > /mysql_backup/$date.$andmebaas.backup.sql 2>/dev/null
