#!/bin/bash

kasutaja=$1

mkdir /home/$kasutaja/public

if [ $? = "0" ]; then
        echo "Kasutaja" $kasutaja "edukalt lisatud!"
else
        echo "Kasutaja loomine ebaõnnestus!"
fi

chown $kasutaja:$kasutaja /home/$kasutaja/public
chmod 751 /home/$kasutaja/public
