#!/bin/bash

kuupaev=$(date +%d.%m.%y)

	for kasutaja in $(awk -F'[/:]' '{if ($3 >= 1000 && $3 != 65534) print $1}' /etc/passwd)
	do
		if [ -f /backup/$nimi.$kuupaev.tar.bz2 ]; then
			echo "Kasutajal $kasutaja on juba backup tehtud"
		else
			tar  -cvjSf /backup/$nimi.$kuupaev.tar.bz2 /home/$nimi 
			echo "$kasutaja backup on tehtud"
fi
done
